// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEFxoZUEHOnC6wkJnC0nQMTRwG-OY7_co',
    appId: '1:16116821579:web:edfd9c1c8c8e7eaf8027ce',
    messagingSenderId: '16116821579',
    projectId: 'fateshly-bf7d6',
    authDomain: 'fateshly-bf7d6.firebaseapp.com',
    storageBucket: 'fateshly-bf7d6.appspot.com',
    measurementId: 'G-MPZPV4ZSK6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVeny67OD7wTYTMouY2PRRyqSGrJsRzQk',
    appId: '1:16116821579:android:332d093a2c4396478027ce',
    messagingSenderId: '16116821579',
    projectId: 'fateshly-bf7d6',
    storageBucket: 'fateshly-bf7d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHBgh8hjijtfMA-RxdAe_vg8matG5H7kU',
    appId: '1:16116821579:ios:74b9e211f528ceea8027ce',
    messagingSenderId: '16116821579',
    projectId: 'fateshly-bf7d6',
    storageBucket: 'fateshly-bf7d6.appspot.com',
    iosBundleId: 'com.example.fateshny',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHBgh8hjijtfMA-RxdAe_vg8matG5H7kU',
    appId: '1:16116821579:ios:34527003333365fc8027ce',
    messagingSenderId: '16116821579',
    projectId: 'fateshly-bf7d6',
    storageBucket: 'fateshly-bf7d6.appspot.com',
    iosBundleId: 'com.example.fateshny.RunnerTests',
  );
}
